travis:
  secure:
    BINSTAR_TOKEN: EUyLcL2b3UCRnNTvuYUx6TCMyt9Z/yFcBqQC6GrZC/wHv0/jnduNfuKBvDPcR3cRs3FheMObmtRFRoVewjz4hE7oDETVYQyEQBdwLVn+4lPzK+8GdN+m0Hh3GzW3UjIVnOyxJhDcxVa8InvpBJf5pEnCOy/MwDMh6ZX9KDt4kbZxSxNaFpdtWFTBaPmG4vwfB6Yf8wY8d9wqTkywRSwcL0c186drT4D+5/AuDruK3699nDN+6HW7diXnf7En7/YGIoLHtk9vXMKsMfHwYTHECYHbYOM9iqvOjKhC4POHGZ3JbGmhnN2A1xOe9N2qicRzvFdW6GWnhvz1LPPOErjmE5Lqlv818swwOm5K8xN+dfQq06TBqO34Nzk8K4nAFKInjyED8qzfZXXvRx2J6f6Sv7Ap0ivftDW/raKA8fUccLwYUOFJ7x5pUdzt8GwNe+GqWpB6yceM8hGbAvVOsO/1404DD+tNTTErXiIP9ej3T3EsRB7CSc7lGZBBJrnKSrHtNlQcLEhJOetUHWwh9bR2cACrOFdxh7qlhY2Ke7Hhx0ux+xAH4MBtIKrVsdGCLXejzDDmwuK3BOtGkMnRFcdoRsIqmpurUv0Spszcmbvl2XHtEtg0XRpY4iwh9ed2EpKCxPoX9ZyqRyEPzBjhlv8v6VrGb9QhckZxMPJlKOPc07E=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
